# @package _global_

defaults:  
  - __init__
  - _self_

# app
app:
  # common
  cls: fine.PDRA

  # pre-defined model specific
  model:
    mask_ks: 3
    maskcache_thres: 0.001
    fastcolor_thres: 0.0001

    stepsize: 0.5

    color_dim: 6
    rgbnet_width: 192
    rgbnet_depth: 4
    
    tonemap_width: 192
    tonemap_depth: 2
    
    brdfnet_width: 128 # 192
    brdfnet_depth: 4

    env_sg: 48
    env_activation: softplus
    
    posbase_pe: 5
    viewbase_pe: 1
    colorbase_pe: 5
    grad_feat: [0.5, 1.0, 1.5, 2.0]

    neus_alpha: interp

    ray_sampling: random
    ray_sampling_eval: fib
    num_2ndrays: 256 
    num_ltspts: 100 
    lts_near: 1e-5

  # trainer
  trainer:
    # model related
    ckpt: null

    brdf_color_init: False 

    s_start: 220.0
    s_inv_ratio: 100.0
    step_start: 0
    step_end: 0

    group_interval: 200
    prog_start: 0.2
    prog_slope: 0.0003
    prog_end_step: 80000 

    # optimizer params
    uncert_batch_size: 8192
    cert_batch_size: 8192
    n_iters: 80000

    lrs:
      off_color: 0.01
      off_rgbnet: 0.0003
      emo_color: 0.001
      emo_rgbnet: 1.0e-05 
      sdf: 5.0e-07 
      tonemapper: 0.0003
      brdf: 0.0001
      brdfnet: 1.0e-06
      emitnet: 1.0e-05
      envmap: 1.0e-05

    decay_steps: {}

    warm_up_iters: 0
    warm_up_min_ratio: 1.0
    const_warm_up: True
    cos_min_ratio: 0

    # reg
    weight_entropy_last: 0.001
    weight_tv_density: 0.01   
    weight_linear: 10.0 #0.1
    weight_normal_smooth: 0.001
    weight_emit_smooth: 0.1
    weight_lts: 0.01
    weight_lts_l: 50.0
    weight_lts_r: 1.0
    weight_emit_supp: 0.1 
    normal_eps: 0.01 
    emit_eps: 0.001

    tvs: 
      sdf: 0.1
      smooth_grad: 0.05

    tv_from: 0
    tv_end: 30000
    tv_every: 3
    tv_dense_before: 20000

    # eval
    em_every: 200 
    vis_every: 10000
    N_vis: -1 
    save_every: 10000
    save_all: False


  eval:
    ckpt: null

    batch_size: 8192

    render_pbr: False 
    chunk_size: 256 

    envmap_height: 128
    envmap_width: 256 

    uncert_batch_size: 4096
    cert_batch_size: 4096
    n_iters: 20000

    mask_dilation_ks: 10

    lrs:
      emo_color: 0.001
      emo_rgbnet: 1.0e-05 

    weight_lts: 0.5
